MAP_DIRECTORY_NAME = "map"
RESULTS_DIRECTORY_NAME = "results"

MAP_IMAGE_FILENAME = "map.png"
MAP_DATA_FILENAME = "map.json"
RUN_LOG_FILENAME = "log.txt"

OPTIMAL_PATH_IMAGE_FILENAME = "optimal_path.png"
ALTERNATIVE_PATH_IMAGE_FILENAME = "alternative_path.png"
PATH_COMPARISON_IMAGE_FILENAME = "path_comparison.png"
CHANGES_IMAGE_FILENAME = "changes.png"
CHANGES_AND_PATHS_IMAGE_FILENAME = "changes_and_paths.png"

RESULT_IMAGE_FILENAMES = (
    OPTIMAL_PATH_IMAGE_FILENAME,
    ALTERNATIVE_PATH_IMAGE_FILENAME,
    PATH_COMPARISON_IMAGE_FILENAME,
    CHANGES_IMAGE_FILENAME,
    CHANGES_AND_PATHS_IMAGE_FILENAME,
)

OUTPUT_ARTIFACT_FILENAMES = (
    MAP_IMAGE_FILENAME,
    *RESULT_IMAGE_FILENAMES,
    MAP_DATA_FILENAME,
    RUN_LOG_FILENAME,
)
